apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: igbo-web-hpa
  namespace: { { .Values.namespace } }
  labels:
    app: igbo-web
    app.kubernetes.io/name: { { .Chart.Name } }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: igbo-web
  minReplicas: { { .Values.web.hpa.minReplicas } }
  maxReplicas: { { .Values.web.hpa.maxReplicas } }
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: { { .Values.web.hpa.targetCPUUtilization } }
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: { { .Values.web.hpa.targetMemoryUtilization } }
