export const PORTAL_ERRORS = {
  ROLE_MISMATCH: "PORTAL_ERRORS.ROLE_MISMATCH",
  NOT_FOUND: "PORTAL_ERRORS.NOT_FOUND",
  COMPANY_REQUIRED: "PORTAL_ERRORS.COMPANY_REQUIRED",
  DUPLICATE_COMPANY_PROFILE: "PORTAL_ERRORS.DUPLICATE_COMPANY_PROFILE",
  POSTING_LIMIT_EXCEEDED: "PORTAL_ERRORS.POSTING_LIMIT_EXCEEDED",
  DUPLICATE_APPLICATION: "PORTAL_ERRORS.DUPLICATE_APPLICATION",
  INVALID_STATUS_TRANSITION: "PORTAL_ERRORS.INVALID_STATUS_TRANSITION",
  ALREADY_SHARED: "PORTAL_ERRORS.ALREADY_SHARED",
} as const;

export type PortalErrorCode = (typeof PORTAL_ERRORS)[keyof typeof PORTAL_ERRORS];
