import "server-only";
import { z } from "zod/v4";
import { canCreateEvent } from "@/services/permissions";
import { ApiError } from "@/lib/api-error";
import { eventBus } from "@/services/event-bus";
import {
  createEvent as dbCreateEvent,
  updateEvent as dbUpdateEvent,
  cancelEvent as dbCancelEvent,
  getEventById,
  rsvpToEvent as dbRsvpToEvent,
  cancelRsvp as dbCancelRsvp,
  cancelAllEventRsvps,
} from "@/db/queries/events";

// ─── Schemas ──────────────────────────────────────────────────────────────────

export const CreateEventSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(5000).optional(),
  eventType: z.enum(["general", "group"]).default("general"),
  groupId: z.string().uuid().optional(),
  format: z.enum(["virtual", "in_person", "hybrid"]).default("virtual"),
  location: z.string().max(500).optional(),
  meetingLink: z.string().url().optional().or(z.literal("")),
  timezone: z.string().min(1).max(50).default("UTC"),
  startTime: z.string().datetime(),
  endTime: z.string().datetime(),
  registrationLimit: z.number().int().positive().optional(),
  recurrencePattern: z.enum(["none", "daily", "weekly", "monthly"]).default("none"),
});
export type CreateEventInput = z.infer<typeof CreateEventSchema>;

export const UpdateEventSchema = CreateEventSchema.omit({
  eventType: true, // event type cannot be changed after creation
  groupId: true, // group association cannot be changed after creation
  recurrencePattern: true, // recurrence cannot be changed after creation
}).partial();
export type UpdateEventInput = z.infer<typeof UpdateEventSchema>;

// ─── Recurrence constants ─────────────────────────────────────────────────────

const RECURRENCE_INSTANCE_COUNTS = {
  daily: 7,
  weekly: 8,
  monthly: 6,
} as const;

const RECURRENCE_OFFSETS_MS = {
  daily: 24 * 60 * 60 * 1000,
  weekly: 7 * 24 * 60 * 60 * 1000,
} as const;

// ─── Service functions ────────────────────────────────────────────────────────

export async function createEvent(
  userId: string,
  data: CreateEventInput,
): Promise<{ eventId: string }> {
  // Permission check
  const permission = await canCreateEvent(userId);
  if (!permission.allowed) {
    throw new ApiError({ title: permission.reason ?? "Forbidden", status: 403 });
  }

  const now = new Date();
  const startTime = new Date(data.startTime);
  const endTime = new Date(data.endTime);

  // Validate startTime is in the future
  if (startTime <= now) {
    throw new ApiError({ title: "Events.validation.futureDate", status: 422 });
  }

  // Validate endTime > startTime
  if (endTime <= startTime) {
    throw new ApiError({ title: "Events.validation.endAfterStart", status: 422 });
  }

  // Validate groupId required for group events
  if (data.eventType === "group" && !data.groupId) {
    throw new ApiError({ title: "Events.validation.groupRequired", status: 422 });
  }

  const durationMinutes = Math.ceil((endTime.getTime() - startTime.getTime()) / 60000);

  // TODO(Story 7.3): meeting_link for virtual events will be auto-generated by Daily.co SDK
  // and will overwrite this field
  const event = await dbCreateEvent({
    title: data.title,
    description: data.description ?? null,
    creatorId: userId,
    groupId: data.groupId ?? null,
    eventType: data.eventType,
    format: data.format,
    location: data.location ?? null,
    meetingLink: data.meetingLink || null,
    timezone: data.timezone,
    startTime,
    endTime,
    durationMinutes,
    registrationLimit: data.registrationLimit ?? null,
    recurrencePattern: data.recurrencePattern,
    status: "upcoming",
  });

  // Generate recurrence instances if needed
  if (data.recurrencePattern !== "none") {
    await generateRecurrenceInstances(event, data.recurrencePattern, durationMinutes);
  }

  await eventBus.emit("event.created", {
    eventId: event.id,
    creatorId: userId,
    title: event.title,
    eventType: event.eventType,
    format: event.format,
    startTime: event.startTime.toISOString(),
    groupId: event.groupId ?? undefined,
    timestamp: new Date().toISOString(),
  });

  return { eventId: event.id };
}

async function generateRecurrenceInstances(
  parent: Awaited<ReturnType<typeof dbCreateEvent>>,
  pattern: "daily" | "weekly" | "monthly",
  durationMinutes: number,
): Promise<void> {
  const count = RECURRENCE_INSTANCE_COUNTS[pattern];
  const instances = [];

  for (let i = 1; i <= count; i++) {
    let instanceStart: Date;
    let instanceEnd: Date;

    if (pattern === "monthly") {
      instanceStart = new Date(parent.startTime);
      instanceStart.setMonth(instanceStart.getMonth() + i);
      instanceEnd = new Date(parent.endTime);
      instanceEnd.setMonth(instanceEnd.getMonth() + i);
    } else {
      const offsetMs = RECURRENCE_OFFSETS_MS[pattern];
      instanceStart = new Date(parent.startTime.getTime() + i * offsetMs);
      instanceEnd = new Date(parent.endTime.getTime() + i * offsetMs);
    }

    instances.push(
      dbCreateEvent({
        title: parent.title,
        description: parent.description,
        creatorId: parent.creatorId,
        groupId: parent.groupId,
        eventType: parent.eventType,
        format: parent.format,
        location: parent.location,
        meetingLink: parent.meetingLink,
        timezone: parent.timezone,
        startTime: instanceStart,
        endTime: instanceEnd,
        durationMinutes,
        registrationLimit: parent.registrationLimit,
        recurrencePattern: "none", // instances are standalone
        recurrenceParentId: parent.id,
        status: "upcoming",
      }),
    );
  }

  await Promise.all(instances);
}

export async function updateEvent(
  userId: string,
  eventId: string,
  data: UpdateEventInput,
): Promise<{ eventId: string }> {
  const event = await getEventById(eventId);
  if (!event) {
    throw new ApiError({ title: "Not Found", status: 404 });
  }

  if (event.creatorId !== userId) {
    throw new ApiError({ title: "Forbidden", status: 403 });
  }

  // Validate date constraints when start/end times are being updated
  const now = new Date();
  if (data.startTime !== undefined) {
    const newStart = new Date(data.startTime);
    if (newStart <= now) {
      throw new ApiError({ title: "Events.validation.futureDate", status: 422 });
    }
  }
  if (data.startTime !== undefined && data.endTime !== undefined) {
    const newStart = new Date(data.startTime);
    const newEnd = new Date(data.endTime);
    if (newEnd <= newStart) {
      throw new ApiError({ title: "Events.validation.endAfterStart", status: 422 });
    }
  } else if (data.endTime !== undefined && data.startTime === undefined) {
    // Updating only endTime — validate against existing startTime
    const newEnd = new Date(data.endTime);
    if (newEnd <= event.startTime) {
      throw new ApiError({ title: "Events.validation.endAfterStart", status: 422 });
    }
  }

  const updates: Parameters<typeof dbUpdateEvent>[2] = {};
  if (data.title !== undefined) updates.title = data.title;
  if (data.description !== undefined) updates.description = data.description ?? null;
  if (data.format !== undefined) updates.format = data.format;
  if (data.location !== undefined) updates.location = data.location ?? null;
  if (data.meetingLink !== undefined) updates.meetingLink = data.meetingLink || null;
  if (data.timezone !== undefined) updates.timezone = data.timezone;
  if (data.startTime !== undefined) updates.startTime = new Date(data.startTime);
  if (data.endTime !== undefined) updates.endTime = new Date(data.endTime);
  if (data.registrationLimit !== undefined)
    updates.registrationLimit = data.registrationLimit ?? null;
  if (data.startTime !== undefined && data.endTime !== undefined) {
    updates.durationMinutes = Math.ceil(
      (new Date(data.endTime).getTime() - new Date(data.startTime).getTime()) / 60000,
    );
  }

  await dbUpdateEvent(eventId, userId, updates);

  await eventBus.emit("event.updated", {
    eventId,
    updatedBy: userId,
    title: event.title,
    timestamp: new Date().toISOString(),
  });

  return { eventId };
}

/**
 * RSVP a user to an event. Handles waitlist logic.
 * Returns { status, waitlistPosition, attendeeCount } on success.
 * Throws ApiError 404/409/422 on failure.
 */
export async function rsvpToEvent(
  userId: string,
  eventId: string,
): Promise<{
  status: "registered" | "waitlisted";
  waitlistPosition: number | null;
  attendeeCount: number;
}> {
  const result = await dbRsvpToEvent(eventId, userId);
  if (!result.success) {
    throw new ApiError({ title: result.reason, status: result.code });
  }

  await eventBus.emit("event.rsvp", {
    eventId,
    userId,
    status: result.status,
    waitlistPosition: result.waitlistPosition,
    attendeeCount: result.attendeeCount,
    timestamp: new Date().toISOString(),
  });

  return {
    status: result.status,
    waitlistPosition: result.waitlistPosition,
    attendeeCount: result.attendeeCount,
  };
}

/**
 * Cancel a user's RSVP for an event. Triggers waitlist promotion if applicable.
 * Throws ApiError 404 if no RSVP found, 409 if already cancelled.
 */
export async function cancelEventRsvp(userId: string, eventId: string): Promise<void> {
  // Get event title for the waitlist promotion notification payload
  const event = await getEventById(eventId);
  if (!event) throw new ApiError({ title: "Event not found", status: 404 });

  const result = await dbCancelRsvp(eventId, userId);
  if (!result.success) {
    throw new ApiError({ title: result.reason, status: result.code });
  }

  await eventBus.emit("event.rsvp_cancelled", {
    eventId,
    userId,
    previousStatus: result.previousStatus,
    attendeeCount: result.attendeeCount,
    timestamp: new Date().toISOString(),
  });

  // Emit waitlist promotion event for the promoted user (if any)
  if (result.promotedUserId) {
    await eventBus.emit("event.waitlist_promoted", {
      eventId,
      promotedUserId: result.promotedUserId,
      title: event.title,
      startTime: event.startTime.toISOString(),
      timestamp: new Date().toISOString(),
    });
  }
}

export async function cancelEvent(userId: string, eventId: string): Promise<void> {
  const event = await getEventById(eventId);
  if (!event) {
    throw new ApiError({ title: "Not Found", status: 404 });
  }

  if (event.creatorId !== userId) {
    throw new ApiError({ title: "Forbidden", status: 403 });
  }

  if (event.status === "cancelled") {
    throw new ApiError({ title: "Already cancelled", status: 422 });
  }

  const cancelled = await dbCancelEvent(eventId, userId);
  if (!cancelled) {
    throw new ApiError({ title: "Status conflict", status: 409 });
  }

  // Cascade: mark all registered/waitlisted attendees as cancelled
  await cancelAllEventRsvps(eventId);

  await eventBus.emit("event.cancelled", {
    eventId,
    cancelledBy: userId,
    title: event.title,
    timestamp: new Date().toISOString(),
  });
}
