import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod/v4";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    DATABASE_POOL_SIZE: z.coerce.number().int().positive().default(20),
    REDIS_URL: z.string().min(1),
    ADMIN_EMAIL: z.email(),
    ADMIN_PASSWORD: z.string().min(8),
    AUTH_SECRET: z.string().min(1),
    AUTH_URL: z.url().optional(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    MAX_SESSIONS_PER_USER: z.coerce.number().int().positive().default(5),
    SESSION_TTL_SECONDS: z.coerce.number().int().positive().default(86400),
    ACCOUNT_LOCKOUT_SECONDS: z.coerce.number().int().positive().default(900),
    ACCOUNT_LOCKOUT_ATTEMPTS: z.coerce.number().int().positive().default(5),
    FACEBOOK_APP_ID: z.string().optional(),
    FACEBOOK_APP_SECRET: z.string().optional(),
    LINKEDIN_CLIENT_ID: z.string().optional(),
    LINKEDIN_CLIENT_SECRET: z.string().optional(),
    X_CLIENT_ID: z.string().optional(),
    X_CLIENT_SECRET: z.string().optional(),
    INSTAGRAM_APP_ID: z.string().optional(),
    INSTAGRAM_APP_SECRET: z.string().optional(),
    // Hetzner Object Storage (S3-compatible)
    HETZNER_S3_ENDPOINT: z.string().min(1),
    HETZNER_S3_REGION: z.string().min(1),
    HETZNER_S3_BUCKET: z.string().min(1),
    HETZNER_S3_ACCESS_KEY_ID: z.string().min(1),
    HETZNER_S3_SECRET_ACCESS_KEY: z.string().min(1),
    HETZNER_S3_PUBLIC_URL: z.string().min(1),
    // ClamAV (optional)
    ENABLE_CLAMAV: z.string().optional().default("false"),
    CLAMAV_HOST: z.string().optional().default("clamav"),
    CLAMAV_PORT: z.coerce.number().int().positive().optional().default(3310),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.url(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_POOL_SIZE: process.env.DATABASE_POOL_SIZE,
    REDIS_URL: process.env.REDIS_URL,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NODE_ENV: process.env.NODE_ENV,
    MAX_SESSIONS_PER_USER: process.env.MAX_SESSIONS_PER_USER,
    SESSION_TTL_SECONDS: process.env.SESSION_TTL_SECONDS,
    ACCOUNT_LOCKOUT_SECONDS: process.env.ACCOUNT_LOCKOUT_SECONDS,
    ACCOUNT_LOCKOUT_ATTEMPTS: process.env.ACCOUNT_LOCKOUT_ATTEMPTS,
    FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
    FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
    LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
    LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET,
    X_CLIENT_ID: process.env.X_CLIENT_ID,
    X_CLIENT_SECRET: process.env.X_CLIENT_SECRET,
    INSTAGRAM_APP_ID: process.env.INSTAGRAM_APP_ID,
    INSTAGRAM_APP_SECRET: process.env.INSTAGRAM_APP_SECRET,
    HETZNER_S3_ENDPOINT: process.env.HETZNER_S3_ENDPOINT,
    HETZNER_S3_REGION: process.env.HETZNER_S3_REGION,
    HETZNER_S3_BUCKET: process.env.HETZNER_S3_BUCKET,
    HETZNER_S3_ACCESS_KEY_ID: process.env.HETZNER_S3_ACCESS_KEY_ID,
    HETZNER_S3_SECRET_ACCESS_KEY: process.env.HETZNER_S3_SECRET_ACCESS_KEY,
    HETZNER_S3_PUBLIC_URL: process.env.HETZNER_S3_PUBLIC_URL,
    ENABLE_CLAMAV: process.env.ENABLE_CLAMAV,
    CLAMAV_HOST: process.env.CLAMAV_HOST,
    CLAMAV_PORT: process.env.CLAMAV_PORT,
  },
});
